version: '3.8'

services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=first_project
      - POSTGRES_PASSWORD=first_project
      - POSTGRES_DB_NAME=first_project
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://first_project:first_project@db:5432/first_project?sslmode=disable
    depends_on:
      - db

volumes:
  postgres_data: